feat(solvcon): add sqlite for python build on mac
The mac OS used by github action does not provide compatible sqlite lib
when building python[1]. This commit will build sqlite for python.

[1] You may get error messages like this:
error: System version of SQLite does not support loadable extensions
make: *** [sharedmods] Error 1