ci(dep): lock numpy to 1.21.4
The latest numpy seems to change its distribution approach so
numpy/distutils/command/build_ext.py does not support
extra_c_compile_argsin the way we expected to cause the following error:

    /usr/lib/python3.8/site-packages/numpy/distutils/command/build_ext.py", line 380,
    in build_extension extra_cflags = ext.extra_c_compile_args or [] AttributeError:
    'Extension' object has no attribute 'extra_c_compile_args'
    make: *** [Makefile:84: legacy] Error 1

Let us keep using numpy 1.21.4 until we fix this issue.

Issue: #98 #103